import { toggleMenu, closeMenu, linkAction } from './nav.js'
import { scrollHeader, scrollActive, scrollUp } from './scroll.js'
import { sr } from './reveal.js'
import { calculateBmi } from './bmi.js'
import { sendEmail } from './contact.js'